### PR TITLE
Copy target audio file to the temp directory

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 150 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/417#-MnzmXXQ4ha_wgj9v7vr:-MnzmXXQ4ha_wgj9v7vs:bb49qdr) ([raw file](https://github.com/bible-translation-tools/orature/blob/e633faf786eb993863cb5ef166cc1927f0859cb3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L150)):*
> ```Kotlin
>                         ".${it.file.extension}"
>                     )
>                     it.file.copyTo(tempFile, true)
> ```

We should clean up this file when the target audio changes

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 150 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/417#-MnzmXXQ4ha_wgj9v7vr:-MnztxiF0tBvUmWGYJh2:b-j0vdvi) ([raw file](https://github.com/bible-translation-tools/orature/blob/e633faf786eb993863cb5ef166cc1927f0859cb3/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L150)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Why? It's just a temporary file. It will be deleted on the next startup.
</blockquote></details>

While that's true, since these are chapters they could be big files (and WAV since they're user recordings not source audio). Seems like you could get a couple hundred megabytes during a days use before you close Orature and start up again. We should also probably add delete on exist before the file is returned from the Directory Provider to try to clean up when the app closes (though it's less reliable than deleting on app startup, so that's still a good fallback)

**Review by jsarabia — CHANGES_REQUESTED** [review]
What kinds of things did you do to test this bug fix?

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417#-:-Mo5cuVY53QWzaM5UiIr:bjswj8m)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt, line 148 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo5L_Wx6yuR0R-sMkvW:-Mo5L_Wx6yuR0R-sMkvX:bnqu57p) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L148)):*
> ```Kotlin
>         }
>         workbookDataStore.sourceAudioProperty.value?.let { source ->
>             val audioPlayer = (app as OtterApp).dependencyGraph.injectPlayer()
> ```

but you'd leave this one untouched?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt, line 148 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo5L_Wx6yuR0R-sMkvW:-Mo8tW-h4udkKmtnCNIt:b-q3mdgs) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L148)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

but you'd leave this one untouched?
</blockquote></details>

What do you mean? This is unrelated to the target audio

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt, line 148 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo5L_Wx6yuR0R-sMkvW:-Mo8xGZAENrVMrP5Y6Cv:bgampgp) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt#L148)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

What do you mean? This is unrelated to the target audio
</blockquote></details>

I don't think the refactor is necessary for the bugfix either but it's there, so when you have two blocks of code doing the same thing for loading audio, I'm not sure why you'd change one and leave the other?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 166 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo94WuhBQ8cc8ITVE7b:-Mo94WuhBQ8cc8ITVE7c:b-dfbzq2) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L166)):*
> ```Kotlin
>     }
> 
>     private fun updateTargetAudio(file: File) {
> ```

We shouldn't mix and match naming conventions; if you like Target Audio, use Target Audio everywhere, if you like Selected Chapter, use Selected Chapter everywhere
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 167 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo973X0EYTFwk3B-ZMu:-Mo973X0EYTFwk3B-ZMv:b-cfezgb) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L167)):*
> ```Kotlin
> 
>     private fun updateTargetAudio(file: File) {
>         when (targetAudioProperty.value?.file?.nameWithoutExtension?.startsWith(file.nameWithoutExtension)) {
> ```

probably worth capturing the values in these expressions into variables, so that the when statement can become more readable

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt, line 166 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/417#-Mo94WuhBQ8cc8ITVE7b:-MoEHJN73Qiw26b4ZsFe:baq7utm) ([raw file](https://github.com/bible-translation-tools/orature/blob/5e500c0e216fb910481be8d244a1898634cbe2cf/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/WorkbookDataStore.kt#L166)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

We shouldn't mix and match naming conventions; if you like Target Audio, use Target Audio everywhere, if you like Selected Chapter, use Selected Chapter everywhere
</blockquote></details>

Selected chapter i different from target audio. Selected chapter should be editable, and target audio not. Selected chapter audio is in Orature data directory, but target audio files are in the temp directory. That's why I separated them into two different properties. Is that what you meant?

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/417#-:-MoK3_9yAVjsQ8UeO7gU:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
