### PR TITLE
Optimization: markerapp low fps for long audio

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt, line 76 at r24](https://reviewable.io/reviews/bible-translation-tools/orature/358#-MlAkRwX5tcwUlO8u3zt:-MlAkRwX5tcwUlO8u3zu:b-5fog1j) ([raw file](https://github.com/bible-translation-tools/orature/blob/14b1a0a45b57f50004edf61bbc0dac3e0dbc453c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt#L76)):*
> ```Kotlin
>         width: Int = Screen.getMainScreen().platformWidth,
>         height: Int = Screen.getMainScreen().platformHeight,
>         waveform: ReplayRelay<Image>
> ```

This is a waveform image builder; its output is a stream of images. It should return an Observable<Image>. Your relay is an observable source, and it should be an internal private implementation detail of the builder- it should not be owned by something OUTSIDE of the builder.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt, line 76 at r24](https://reviewable.io/reviews/bible-translation-tools/orature/358#-MlAkRwX5tcwUlO8u3zt:-MlBbK2I8D_Vj8dqwlNn:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/14b1a0a45b57f50004edf61bbc0dac3e0dbc453c/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt#L76)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This is a waveform image builder; its output is a stream of images. It should return an Observable<Image>. Your relay is an observable source, and it should be an internal private implementation detail of the builder- it should not be owned by something OUTSIDE of the builder.
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r11, 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt, line 94 at r26](https://reviewable.io/reviews/bible-translation-tools/orature/358#-MlBdASB5qUNKyWr3Cos:-MlBdASB5qUNKyWr3Cot:bozt9vj) ([raw file](https://github.com/bible-translation-tools/orature/blob/bf1ddb5413fb2514042c51e53c0530dd56f3257b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt#L94)):*
> ```Kotlin
> 
>         return waveformStream
>             .observeOnFx()
> ```

Let the consumer decide where they want to observe.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt, line 94 at r26](https://reviewable.io/reviews/bible-translation-tools/orature/358#-MlBdASB5qUNKyWr3Cos:-MlBmMwo3iK4VF9-cwPN:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/bf1ddb5413fb2514042c51e53c0530dd56f3257b/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/waveform/WaveformImageBuilder.kt#L94)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Let the consumer decide where they want to observe.
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/358#-:-MlBmx1H2XlzCTGRBG_t:bnfp4nl)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

**Pull request merged**
