### PR TITLE
Apply breadcrumbs and Navigation Mediator

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/262)

### CODE REVIEW

**Review by jsarabia — COMMENTED** [review]
The size of the bar and items are changing when you move to different pages; This shouldn't be happening.
The background color is off, and the takes page grid isn't centered anymore?

> Reviewed 24 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/262#-:-MYM6oH08RtrSKFaDT0p:b-u7p587)* status: 24 of 37 files reviewed, all discussions resolved (waiting on @mXaln)

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/262)* status: 24 of 37 files reviewed, 7 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/plugin/AudioPlugin.kt, line 37 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMGetV2fdJx-9gppbC:-MYMGetV2fdJx-9gppbD:b7ax2ni) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/plugin/AudioPlugin.kt#L37)):*
> ```Kotlin
> 
>     override fun quit() {
>         process?.destroy()
> ```

I don't want us to kill the process. Especially without alerting the user; we dont know how much work they could accidentally lose this way, or if it would corrupt data as a result. I don't even allow the app window to close now when a plugin is opened.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt, line 129 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHA_b6IxWkPD5CO4d:-MYMHA_cB3fqiIp4VK2Y:b-xbf2tt) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt#L129)):*
> ```Kotlin
>     }
> 
>     private fun breadcrumbTitleBinding(): StringBinding {
> ```

this looks like functionality that should go in the viewmodel? (Title building)
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordResourcePage.kt, line 36 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHebY9cpuHgeDvsdC:-MYMHebZ6vlubMXQ1h06:bsl5o3d) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordResourcePage.kt#L36)):*
> ```Kotlin
>     private val breadCrumb = BreadCrumb().apply {
>         titleProperty.bind(
>             currentTakeNumberProperty.stringBinding {
> ```

this property should probably be in the viewmodel
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt, line 93 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHswe8GZJpHX-9Jq9:-MYMHswe8GZJpHX-9JqA:bupwx1b) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt#L93)):*
> ```Kotlin
>                 } ?: messages["take"]
>             }
>         )
> ```

viewmodel
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ResourcePage.kt, line 75 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMI2x5CrGTdgxnJ8bE:-MYMI2x5CrGTdgxnJ8bF:bupwx1b) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ResourcePage.kt#L75)):*
> ```Kotlin
> 
>     private fun breadcrumbTitleBinding(): StringBinding {
>         return Bindings.createStringBinding(
> ```

viewmodel
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RootView.kt, line 43 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMIGU35b9FfoMtNrez:-MYMIGU35b9FfoMtNrf-:bci9h1c) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RootView.kt#L43)):*
> ```Kotlin
>         borderpane {
>             top = menu
>             center = vbox {
> ```

this probably should be another borderpane until we can remove the menu. This is probably why the height of the bar is jumping around.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 46 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMIU4lDAYe5hpLqUVT:-MYMIU4lDAYe5hpLqUVU:bupwx1b) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L46)):*
> ```Kotlin
> 
>     private val breadCrumb = BreadCrumb().apply {
>         titleProperty.bind(
> ```

viewmodel

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/otter/262)* status: 12 of 40 files reviewed, 7 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/plugin/AudioPlugin.kt, line 37 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMGetV2fdJx-9gppbC:-MYPa4ZGDP9_NUySvwIY:b-2ojg2x) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/plugin/AudioPlugin.kt#L37)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't want us to kill the process. Especially without alerting the user; we dont know how much work they could accidentally lose this way, or if it would corrupt data as a result. I don't even allow the app window to close now when a plugin is opened.
</blockquote></details>

ok, done
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt, line 129 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHA_b6IxWkPD5CO4d:-MYPa7-k5ty5tIaz25F6:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ChapterPage.kt#L129)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this looks like functionality that should go in the viewmodel? (Title building)
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordResourcePage.kt, line 36 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHebY9cpuHgeDvsdC:-MYPaaRt9FczYCJNvBV7:blis2z3) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordResourcePage.kt#L36)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this property should probably be in the viewmodel
</blockquote></details>

yeah, that's a better place for it. Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt, line 93 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMHswe8GZJpHX-9Jq9:-MYPboPK1ay7InvIMFhs:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RecordScripturePage.kt#L93)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

viewmodel
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ResourcePage.kt, line 75 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMI2x5CrGTdgxnJ8bE:-MYPbqjCCIxUZob_lXWV:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/ResourcePage.kt#L75)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

viewmodel
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RootView.kt, line 43 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMIGU35b9FfoMtNrez:-MYPeDBH1dCACLNIgzJl:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/RootView.kt#L43)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this probably should be another borderpane until we can remove the menu. This is probably why the height of the bar is jumping around.
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 46 at r1](https://reviewable.io/reviews/bible-translation-tools/otter/262#-MYMIU4lDAYe5hpLqUVT:-MYPbw8cDIxu0sGCj27c:b-896fix) ([raw file](https://github.com/bible-translation-tools/otter/blob/32fcb5d1dc4b051b5c0f039105ce601352f62e55/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L46)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

viewmodel
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/262#-:-MZEMCIN5iH7cRD3Awre:bnfp4nl)* status: 11 of 41 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
