### PR TITLE
Created app drawer

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/271)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/271)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 53 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/271#-MZEjU2E5CdHUFySvE_r:-MZEjU2E5CdHUFySvE_s:b3w2q5q) ([raw file](https://github.com/bible-translation-tools/orature/blob/0319d63e3b09dd64251d5ea7a01d0229578ab799/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L53)):*
> ```Kotlin
>                     isDisable = true
>                 }
>             )
> ```

we probably don't want to add this button to the bar until the functionality is there. We may never prioritize it, and then there'd just always be this disabled button there which would be confusing,.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/271#-MZEjlp55WiXSg7cYpSb:-MZEjlp55WiXSg7cYpSc:bhdjuvd) ([raw file](https://github.com/bible-translation-tools/orature/blob/0319d63e3b09dd64251d5ea7a01d0229578ab799/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L89)):*
> ```Kotlin
> 
>     private inline fun <reified T: UIComponent> toggleOpen(isActive: Boolean) {
>         if (isActive) {
> ```

maybe a when statement would be better here

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/271)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 53 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/271#-MZEjU2E5CdHUFySvE_r:-MZHuhuk6yb1XpIRmRJg:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0319d63e3b09dd64251d5ea7a01d0229578ab799/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L53)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

we probably don't want to add this button to the bar until the functionality is there. We may never prioritize it, and then there'd just always be this disabled button there which would be confusing,.
</blockquote></details>

Done.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/271)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/271#-MZEjlp55WiXSg7cYpSb:-MZHwOlN-vjKj9gf1AES:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/0319d63e3b09dd64251d5ea7a01d0229578ab799/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L89)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

maybe a when statement would be better here
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/271#-:-MZItRg83KVPlOzqGLlw:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
