### PR TITLE
Refactor css theme swapping

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Previously, when the system's color preference changes, the css files for dark and light theme are replaced accordingly; this is not efficient. Now, it only needs to replace the css class name instead.

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/418)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/418)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/OtterDialog.kt, line 39 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/418#-Mo92n_G6CmylzRC0Wss:-Mo92n_G6CmylzRC0Wst:b-svc88j) ([raw file](https://github.com/bible-translation-tools/orature/blob/3ac51384651e80b3e135144c47b41e47c8379e28/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/OtterDialog.kt#L39)):*
> ```Kotlin
> 
>     private val osThemeDetector = OsThemeDetector.getDetector()
>     private val isOSDarkMode = SimpleBooleanProperty(osThemeDetector.isDark)
> ```

let's keep consistent with the word "theme" not "mode"

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/418)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/OtterDialog.kt, line 39 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/418#-Mo92n_G6CmylzRC0Wss:-MoAcDSt0ZxWE46WsodR:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/3ac51384651e80b3e135144c47b41e47c8379e28/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/dialog/OtterDialog.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

let's keep consistent with the word "theme" not "mode"
</blockquote></details>

Done.

**Review by mXaln — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/418#-:-MoKZT-R29rnUEhe3T57:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
