### PR TITLE
Artwork with Image Ratio

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 7 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEtQgz7CJN7AU_PIIQ:-MhEtQh-8EQIb3SeHKbP:b-dqm1jm) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L7)):*
> ```Kotlin
>     FOUR_BY_THREE(4, 3),
>     ONE_BY_ONE(1, 1),
>     DEFAULT(0, 0);
> ```

we need 4x1 and 2x1 as well
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 9 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEMf901uFFUwbtzWeZ:-MhEMf917ZIeWqNaGGy2:b4zcw57) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L9)):*
> ```Kotlin
>     DEFAULT(0, 0);
> 
>     fun getStringFormat(): String {
> ```

I think I would change the name to reflect that this is what gets appended to the image. getImageSuffix? or something? idk. I think it should also include the underscore in front, so that you can apend this universally, even in the default case. (one less branching statement)

if you want the aspect ratio name as a string, it's fine to have this method too. Also this could probably honestly be the toString method of this enum class, rather than "getStringFormat"
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt, line 37 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEN1tO8SBRaiXDfLnj:-MhEN1tO8SBRaiXDfLnk:b-utd3od) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt#L37)):*
> ```Kotlin
> 
>     fun getArtwork(imageRatio: ImageRatio = ImageRatio.DEFAULT): File? {
>         imagesDataSources.forEach {
> ```

can you name "it" here?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEtnFZ7fGVMD1OpzuM:-MhEtnFZ7fGVMD1OpzuN:bmfiqla) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt#L38)):*
> ```Kotlin
>     fun getArtwork(imageRatio: ImageRatio = ImageRatio.DEFAULT): File? {
>         imagesDataSources.forEach {
>             var image = it.getImage(metadata, projectSlug, imageRatio)
> ```

I think getImage should handle the default case too, and not use a branch here
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt, line 47 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEuFpO3qzo72VIPDFL:-MhEuFpO3qzo72VIPDFM:b-eceiz3) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt#L47)):*
> ```Kotlin
> 
>         val imagesContainer = directoryProvider.resourceContainerDirectory
>             .resolve(imagesContainerName)
> ```

this would be more easily read by:
```
        val imagesContainer = directoryProvider
                                                   .resourceContainerDirectory
                                                   .resolve(imagesContainerName)

```
rather than arbitrarily breaking the line

https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt, line 70 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEw9vQAuwPQrwufGnW:-MhEw9vQAuwPQrwufGnX:bvi2thv) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt#L70)):*
> ```Kotlin
>                 val imagePath = getImagePathWithRatio(contentPath, imageRatio)
>                 if (!rc.accessor.fileExists(imagePath)) {
>                     return null
> ```

if it doesn't exist and the ratio isn't default, try the default before just aborting
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEwM3X6TCZB1Zgmo98:-MhEwM3X6TCZB1Zgmo99:b-bjmhyn) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L38)):*
> ```Kotlin
>         if (ratio == ImageRatio.DEFAULT) {
>             return path
>         }
> ```

you don't need this to be separate if you create a method that universally returns the file suffix
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 44 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEulkhE_3xnula3BDr:-MhEulkhE_3xnula3BDs:b-xpc6dy) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L44)):*
> ```Kotlin
> 
>         return image.parentFile.resolve(nameWithRatio)
>             .invariantSeparatorsPath
> ```

this doesn't need to be on its own line, it would be roughly as long as the string above
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ResourceContainerImagesDataSource.kt, line 106 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEvUMW2q3Atv0y4IfH:-MhEvUMW2q3Atv0y4IfI:b-dr34yq) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ResourceContainerImagesDataSource.kt#L106)):*
> ```Kotlin
>             if (rc.accessor.fileExists(path)) {
>                 val fileName =
>                     "${language}_${resourceId}_${project}_${File(path).name}"
> ```

you should have enough horizontal space to put this on the line above

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 7 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEtQgz7CJN7AU_PIIQ:-MhF10GS7_L1aMNZSu_R:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

we need 4x1 and 2x1 as well
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 9 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEMf901uFFUwbtzWeZ:-MhF120118ikxBpjADjn:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L9)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I think I would change the name to reflect that this is what gets appended to the image. getImageSuffix? or something? idk. I think it should also include the underscore in front, so that you can apend this universally, even in the default case. (one less branching statement)

if you want the aspect ratio name as a string, it's fine to have this method too. Also this could probably honestly be the toString method of this enum class, rather than "getStringFormat"
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt, line 37 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEN1tO8SBRaiXDfLnj:-MhF8TbS4Jvz5TckDmV9:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt#L37)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can you name "it" here?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt, line 47 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEuFpO3qzo72VIPDFL:-MhF8RxY9-g3xhdcUQTO:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt#L47)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this would be more easily read by:
```
        val imagesContainer = directoryProvider
                                                   .resourceContainerDirectory
                                                   .resolve(imagesContainerName)

```
rather than arbitrarily breaking the line

https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 44 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEulkhE_3xnula3BDr:-MhF8Q-Q8-IMgsREYb-i:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L44)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this doesn't need to be on its own line, it would be roughly as long as the string above
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ResourceContainerImagesDataSource.kt, line 106 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEvUMW2q3Atv0y4IfH:-MhF8OcQC3ZLYQ7zVLmQ:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ResourceContainerImagesDataSource.kt#L106)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you should have enough horizontal space to put this on the line above
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEtnFZ7fGVMD1OpzuM:-MhFH-Yf8XsBa9loz35R:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ArtworkAccessor.kt#L38)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I think getImage should handle the default case too, and not use a branch here
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt, line 70 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEw9vQAuwPQrwufGnW:-MhFH19i-c3C07YV7F_Z:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/BibleImagesDataSource.kt#L70)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

if it doesn't exist and the ratio isn't default, try the default before just aborting
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhEwM3X6TCZB1Zgmo98:-MhFH3eM8G7Bw-uq0flt:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/aa9e47f711b4afebfa4ab5bcd8a24fdb0a38a776/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L38)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

you don't need this to be separate if you create a method that universally returns the file suffix
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 1 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhFVS1c7qLL7ZdHtHg-:-MhFVS1c7qLL7ZdHtHg0:b-v1phy9) ([raw file](https://github.com/bible-translation-tools/orature/blob/7dcceac926054dd7704dff9fa825f389ca0356f3/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L1)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.data.primitives
> ```

file needs license

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt, line 1 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhFVS1c7qLL7ZdHtHg-:-MhFXizZDLnsXLYjc5hr:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/7dcceac926054dd7704dff9fa825f389ca0356f3/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/primitives/ImageRatio.kt#L1)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

file needs license
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 26 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhJ-3MA5GOvE61JprlH:-MhJ-3MA5GOvE61JprlI:b-9fgzlr) ([raw file](https://github.com/bible-translation-tools/orature/blob/b005852dec6415ad583dbd21594b449b394437cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L26)):*
> ```Kotlin
> 
> interface ImagesDataSource {
>     fun getImage(
> ```

could you provide a javadoc comment for this method?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt, line 23 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhIztD5C9Vde5hNGBuL:-MhIztD5C9Vde5hNGBuM:b-ta2r6e) ([raw file](https://github.com/bible-translation-tools/orature/blob/b005852dec6415ad583dbd21594b449b394437cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt#L23)):*
> ```Kotlin
> import java.io.File
> 
> fun filePathWithSuffix(path: String, suffix: String): String {
> ```

could you provide a javadoc comment for this function?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt, line 23 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhIztD5C9Vde5hNGBuL:-MhJIezPELedNnj1fjWz:b-w1wuvn) ([raw file](https://github.com/bible-translation-tools/orature/blob/b005852dec6415ad583dbd21594b449b394437cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt#L23)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

could you provide a javadoc comment for this function?
</blockquote></details>

Can you explain what you mean? After all, a file extension is a suffix

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt, line 23 at r6](https://reviewable.io/reviews/bible-translation-tools/orature/332#-MhIztD5C9Vde5hNGBuL:-MhJPDgJ1j-2v50VdNCd:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b005852dec6415ad583dbd21594b449b394437cd/common/src/main/kotlin/org/wycliffeassociates/otter/common/utils/FileUtils.kt#L23)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Can you explain what you mean? After all, a file extension is a suffix
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/332#-:-MhJgA7HEICtdF_yiiEx:bnfp4nl)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @AnonymousWalker)

**Pull request merged**
