### PR TITLE
Added ability to change the app language

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioDeviceProvider.kt, line 37 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk26Ib28QgCr-W0F9r1:-Mk26Ib28QgCr-W0F9r2:b-f06zz4) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioDeviceProvider.kt#L37)):*
> ```Kotlin
>     val activeOutputDevice: Observable<Mixer.Info> = PublishSubject.create()
> 
>     fun selectInputDevice(device: Mixer.Info) {
> ```

This PR should not have anything involving audio devices.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk273qG2uTXaAeXoPU_:-Mk273qG2uTXaAeXoPUa:b5fhe2e) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt#L32)):*
> ```Kotlin
>     private val appPrefRepo: IAppPreferencesRepository,
>     private val langRepo: ILanguageRepository
> ) : ILocaleLanguage {
> ```

LocaleLanguage is a domain class: it does task kind of work to solve user tasks.

When you make interfaces, you should have a reason to do so. Should it define method names to be implemented by a bunch of different classes? Should it define methods so it can be used generically, so that implementations can be done per platform?

I don't see either of those reasons applying here. Your constructor parameters already take in interfaces, so this code is already common code.

Also, adding @Inject to your constructor already adds this to the dependency graph, so Dagger already knows how to build it. You do not need modules, providers, etc to inject it. You only need to do that when you want to customize HOW it gets built.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AppPreferencesRepository.kt, line 74 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk2923y3Z1ur3tHYdN8:-Mk2923y3Z1ur3tHYdN9:b-gn91ow) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AppPreferencesRepository.kt#L74)):*
> ```Kotlin
>     }
> 
>     override fun setOutputDevice(mixer: Mixer.Info): Completable {
> ```

Don't change the audio parameters.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt, line 29 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk2CsPvADAmHm2HPUht:-Mk2CsPw1jg_i8s0nSNG:b-yx63r4) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt#L29)):*
> ```Kotlin
> import javax.inject.Inject
> 
> class LocaleLanguage @Inject constructor(
> ```

I would probably name the class something more like "ChangeLocale" to reflect its use case nature.

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @Inject and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt, line 29 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk2CsPvADAmHm2HPUht:-Mk2O6ot8dtZytifrY9G:b-mk14m4) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt#L29)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I would probably name the class something more like "ChangeLocale" to reflect its use case nature.
</blockquote></details>

I disagree. This class doesn't do any task so it's not a use case, it only provides with the list of supported and preferred languages
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt, line 32 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk273qG2uTXaAeXoPU_:-Mk2OSBK5-6Bva5YWV6_:b9oos96) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/LocaleLanguage.kt#L32)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

LocaleLanguage is a domain class: it does task kind of work to solve user tasks.

When you make interfaces, you should have a reason to do so. Should it define method names to be implemented by a bunch of different classes? Should it define methods so it can be used generically, so that implementations can be done per platform?

I don't see either of those reasons applying here. Your constructor parameters already take in interfaces, so this code is already common code.

Also, adding @Inject to your constructor already adds this to the dependency graph, so Dagger already knows how to build it. You do not need modules, providers, etc to inject it. You only need to do that when you want to customize HOW it gets built.
</blockquote></details>

Yes, I think it does need the interface, 'cause each platform should implement it's own way of getting the list of supported languages and the preferred language.

Could you show me how to not use module and/or provider, without them it can't inject it.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AppPreferencesRepository.kt, line 74 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk2923y3Z1ur3tHYdN8:-Mk2Ow9F3jlmSH5wSZaP:b32wtd) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/AppPreferencesRepository.kt#L74)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Don't change the audio parameters.
</blockquote></details>

ok
___
*[jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioDeviceProvider.kt, line 37 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk26Ib28QgCr-W0F9r1:-Mk2Ozjf3noGdl9urlQj:b13garo) ([raw file](https://github.com/bible-translation-tools/orature/blob/28b320d487404fd04daad6a345a622f08f449a26/jvm/device/src/main/kotlin/org/wycliffeassociates/otter/jvm/device/audio/AudioDeviceProvider.kt#L37)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This PR should not have anything involving audio devices.
</blockquote></details>

Sure, I'll create a new pr for this

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 1 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)* status: 1 of 26 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ILocaleDataStore.kt, line 3 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3td3s0L9SUwbsMnXe:-Mk3td3s0L9SUwbsMnXf:bm2rhbf) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ILocaleDataStore.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.common.persistence
> 
> interface ILocaleDataStore {
> ```

Ah, sorry, I should have typed out the name! I meant "Data Source," this would effectively wrap the locale properties file which is the source of the data we're using (this class just provides java code to access it)

A store is more like the active State like in Redux (which was kinda the inspiration for the WorkBookDataSource which isn't exactly a ViewModel since it's shared global observable app state.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SplashScreenViewModel.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3vChPBCPDPKY-JjBt:-Mk3vChPBCPDPKY-JjBu:b-vzj1oz) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SplashScreenViewModel.kt#L38)):*
> ```Kotlin
> 
>     @Inject
>     lateinit var appPrefRepo: IAppPreferencesRepository
> ```

it doesn't look like anything in this class is using this dependency?
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/modules/LocaleDataStoreModule.kt, line 29 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3utOf7Pt7YFj3mzWq:-Mk3utOf7Pt7YFj3mzWr:b-o98jzd) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/modules/LocaleDataStoreModule.kt#L29)):*
> ```Kotlin
> abstract class LocaleDataStoreModule {
>     @Binds
>     abstract fun providesLocaleDataStore(dataStore: LocaleDataStore): ILocaleDataStore
> ```

I would probably put this under the repositories module; it's related enough.

**Review by jsarabia — COMMENTED** [review]
I merged in the localization changes to dev so there's some localization files now. I think we should write some tests, which should help verify that the gradle task works correctly and is packaged correctly (along with other tests you can think of).

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356#-:-Mk3y-fx2dzFlv3CJjUb:bde29la)* status: 1 of 26 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356)* status: 1 of 27 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SplashScreenViewModel.kt, line 38 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3vChPBCPDPKY-JjBt:-Mk6up2F1OjJh1T0yTX7:bjzail9) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/SplashScreenViewModel.kt#L38)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

it doesn't look like anything in this class is using this dependency?
</blockquote></details>

good catch. removed.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ILocaleDataStore.kt, line 3 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3td3s0L9SUwbsMnXe:-Mk6uwOL5VjyLCly0l6v:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ILocaleDataStore.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Ah, sorry, I should have typed out the name! I meant "Data Source," this would effectively wrap the locale properties file which is the source of the data we're using (this class just provides java code to access it)

A store is more like the active State like in Redux (which was kinda the inspiration for the WorkBookDataSource which isn't exactly a ViewModel since it's shared global observable app state.
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/modules/LocaleDataStoreModule.kt, line 29 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/356#-Mk3utOf7Pt7YFj3mzWq:-Mk6ut2p94M1xMSXNPla:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d43845ba44cea09f68ccea596d3c7e2c4638844/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/di/modules/LocaleDataStoreModule.kt#L29)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I would probably put this under the repositories module; it's related enough.
</blockquote></details>

Done.

**Review by mXaln — COMMENTED** [review]
Added tests

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356#-:-Mk7SUuC7cz4XiN-zsa0:b-hck6ro)* status: 1 of 29 files reviewed, 4 unresolved discussions (waiting on @jsarabia)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> Reviewed 8 of 24 files at r1, 2 of 5 files at r2, 3 of 9 files at r3, 9 of 11 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/356#-:-Mk8LOkX2eMjSIhaNoYd:bnfp4nl)* status: 26 of 29 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

**Pull request merged**
