### PR TITLE
Artwork Accessor with Multiple Data Sources

### PR DESCRIPTION
**Pull request by AnonymousWalker**
Retrieve book's cover artwork from different Data Sources with specific priority

This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 15 files reviewed, 12 unresolved discussions (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Workbook.kt, line 38 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQmyUAH66tziZLV8u:-MglQmyUAH66tziZLV8v:b-4nc271) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Workbook.kt#L38)):*
> ```Kotlin
>         )
>     }
>     val artworkAccessor: ArtworkAccessor by lazy { ArtworkAccessor(directoryProvider) }
> ```

if there is no longer any state associated with this; as in, it does not contain the state of a workbook (resource metadata and slug), what value is there in having it be a member variable of the Workbook?

In fact, what value is there in having it be a class and not just an object (singleton)?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt, line 33 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglNlo80EkcJ4z6IR-v:-MglNlo80EkcJ4z6IR-w:b-5njuzq) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt#L33)):*
> ```Kotlin
>     fun getArtwork(metadata: ResourceMetadata, projectSlug: String): File? {
>         val imgDataSource1: ImagesDataSource = CustomImagesDataSource()
>         val imgDataSource2: ImagesDataSource = BibleImagesDataSource(directoryProvider, File("""\bible\images\container"""))
> ```

Aside from the code style issue here, I don't like hard cording a string here. If you need it, define it as a constant. But is this an implementation detail of the BIDS?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt, line 34 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglNeOuEJw6PYZ05-_Q:-MglNeOv5TXwb-sd_qAk:bf9ajuy) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt#L34)):*
> ```Kotlin
>         val imgDataSource1: ImagesDataSource = CustomImagesDataSource()
>         val imgDataSource2: ImagesDataSource = BibleImagesDataSource(directoryProvider, File("""\bible\images\container"""))
>         val imgDataSource3: ImagesDataSource = DefaultImagesDataSource()
> ```

why do these need to be created each time I go to access artwork?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt, line 12 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglO-6541O1Xq6Qm35A:-MglO-6541O1Xq6Qm35B:b-ffufja) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt#L12)):*
> ```Kotlin
> ) : ImagesDataSource() {
> 
>     private val imagesDir = File(directoryProvider.cacheDirectory, "bible-images").apply { mkdirs() }
> ```

line length, also declare the path as a const,
Can this go in the companion object?
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt, line 65 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglTV6j0MOYdHb-ELQA:-MglTV6j0MOYdHb-ELQB:bj22r0c) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt#L65)):*
> ```Kotlin
>             synchronized(filesCache) {
>                 return filesCache["$languageSlug-$resourceId-$project"]
>             }
> ```

using a ConcurrentHashMap is going to be superior if you're going to attempt thread safety
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPXXZ9Da887JK0WbJ:-MglPXXZ9Da887JK0WbK:b-7s4sqq) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt#L8)):*
> ```Kotlin
> class DefaultImagesDataSource : ImagesDataSource() {
>     override fun getImage(metadata: ResourceMetadata, projectSlug: String): File? {
>         return File("""\default\artwork\path""")
> ```

const
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt, line 10 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglOQVF3XxzxWOIbdkZ:-MglOQVF3XxzxWOIbdk_:b-7n5zto) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt#L10)):*
> ```Kotlin
>  */
> abstract class ImagesDataSource {
>     protected var nextDataSource: ImagesDataSource? = null
> ```

I don't agree with doing this. Let a data source attempt to find an image, and if it is found, return it, else, return null. Let the top level Accessor class have a priority list loop over each and break when it finds something not null. No need to make the data sources coupled to the use of them- this mixes responsibilities.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt, line 21 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPCZI53verxKIXEb3:-MglPCZI53verxKIXEb4:b-svoruu) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt#L21)):*
> ```Kotlin
>     }
> 
>     protected fun getImageFromContainer(): File? {
> ```

I would just call this getImage, if you have to have a case which a data source does not refer to a project.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 154 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQ4i-ChNsoGJe6RH0:-MglQ4i-ChNsoGJe6RH1:b8hwadn) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L154)):*
> ```Kotlin
> 
>     private fun initializeDeleteConfirmDialog() {
>         val workbook = viewModel.workbookDataStore.workbook
> ```

this is almost certainly a bug
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 190 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQL-qEKba9Ygg93wH:-MglQL-qEKba9Ygg93wI:byr4ffv) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L190)):*
> ```Kotlin
> 
>     private fun initializeDeleteSuccessDialog() {
>         val workbook = viewModel.workbookDataStore.workbook
> ```

see above
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 222 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQR7O9QxpxV3fZ4X5:-MglQR7O9QxpxV3fZ4X6:byr4ffv) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L222)):*
> ```Kotlin
> 
>     private fun initializeDeleteFailDialog() {
>         val workbook = viewModel.workbookDataStore.workbook
> ```

see above
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt, line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQT-C8U5dlkq7aQQb:-MglQT-C8U5dlkq7aQQc:b-jmceu4) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L40)):*
> ```Kotlin
>     private val viewModel: BookWizardViewModel by inject()
>     private val navigator: NavigationMediator by inject()
> //    @Inject lateinit var directoryProvider: IDirectoryProvider
> ```

don't comment things out; either keep them or delete them.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 15 files reviewed, 12 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Workbook.kt, line 38 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQmyUAH66tziZLV8u:-Mglh1kZ2u83S6ZfS2f6:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Workbook.kt#L38)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

if there is no longer any state associated with this; as in, it does not contain the state of a workbook (resource metadata and slug), what value is there in having it be a member variable of the Workbook?

In fact, what value is there in having it be a class and not just an object (singleton)?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt, line 12 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglO-6541O1Xq6Qm35A:-Mglh7AeDdSdxkxVJ1_v:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt#L12)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

line length, also declare the path as a const,
Can this go in the companion object?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt, line 21 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPCZI53verxKIXEb3:-MglhB0nAANBbG5ta32R:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt#L21)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I would just call this getImage, if you have to have a case which a data source does not refer to a project.
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 154 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQ4i-ChNsoGJe6RH0:-MglhCBL-fslRTaIgWYs:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L154)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this is almost certainly a bug
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 190 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQL-qEKba9Ygg93wH:-MglhCd89-vVbgH3bGJG:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L190)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt, line 222 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQR7O9QxpxV3fZ4X5:-MglhD9nCKimMSGT3Ydx:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/WorkbookPage.kt#L222)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt, line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglQT-C8U5dlkq7aQQb:-MglhE2c-B9SFk7lL3XK:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/book/BookSelection.kt#L40)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

don't comment things out; either keep them or delete them.
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt, line 10 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglOQVF3XxzxWOIbdkZ:-Mglq_tz-Cn3e1kq6ZDs:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/ImagesDataSource.kt#L10)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't agree with doing this. Let a data source attempt to find an image, and if it is found, return it, else, return null. Let the top level Accessor class have a priority list loop over each and break when it finds something not null. No need to make the data sources coupled to the use of them- this mixes responsibilities.
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt, line 33 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglNlo80EkcJ4z6IR-v:-MglqnZt4i-dOxEsmlEP:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt#L33)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Aside from the code style issue here, I don't like hard cording a string here. If you need it, define it as a constant. But is this an implementation detail of the BIDS?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt, line 34 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglNeOuEJw6PYZ05-_Q:-MglqoBNEDh--1JixLHG:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/ArtworkAccessor.kt#L34)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why do these need to be created each time I go to access artwork?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPXXZ9Da887JK0WbJ:-Mglqpaa4LdBgU01NvTc:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 9 at r11](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MgqIPX59e5oUmWmvj6M:-MgqIPX59e5oUmWmvj6N:bvopgnp) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d5d2c607b9f37190e4fc8fce896e2f1d5956cd0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L9)):*
> ```Kotlin
>  * Chain of Responsibility - Base handler class
>  */
> abstract class ImagesDataSource {
> ```

this should just be an interface now
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPXXZ9Da887JK0WbJ:-MgqICBG2255suJ7DGDO:b-tdk299) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt#L8)):*
<details><summary><i>Previously, AnonymousWalker (Tony Anh Tran) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If this is going to be added later; I'd probably just say we should remove it and add it in a new PR, rather than merge half implemented features

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt, line 9 at r11](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MgqIPX59e5oUmWmvj6M:-MgqRrxq0QgjeFvKCOtf:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/4d5d2c607b9f37190e4fc8fce896e2f1d5956cd0/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/artwork/ImagesDataSource.kt#L9)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

this should just be an interface now
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt, line 65 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglTV6j0MOYdHb-ELQA:-MgqRspo1Jh6WI_Iltk7:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/BibleImagesDataSource.kt#L65)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

using a ConcurrentHashMap is going to be superior if you're going to attempt thread safety
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MglPXXZ9Da887JK0WbJ:-MgqRtkB2sP_pFHG5jlv:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e2f9db70ef63ecd9057cbc3beac85de2eb3c1fc0/common/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/DefaultImagesDataSource.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

If this is going to be added later; I'd probably just say we should remove it and add it in a new PR, rather than merge half implemented features
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 1 of 9 files at r6, 1 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327#-:-Mh017Z81oRWnUVRb90Z:bnfp4nl)* status: 3 of 24 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModel.kt, line 131 at r19](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MgzsJC31L4K8SPd7DZF:-MgzsJC31L4K8SPd7DZG:b-141cbk) ([raw file](https://github.com/bible-translation-tools/orature/blob/6e383c7a560929d36dcaeb6ac306eaf2c44af571/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModel.kt#L131)):*
> ```Kotlin
>     private fun loadChildren(parent: Collection) {
> ```

unnecessary white space

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/327)* status: 3 of 24 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModel.kt, line 131 at r19](https://reviewable.io/reviews/bible-translation-tools/orature/327#-MgzsJC31L4K8SPd7DZF:-Mh01Z0_-mImeKTYEKOR:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/6e383c7a560929d36dcaeb6ac306eaf2c44af571/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/BookWizardViewModel.kt#L131)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

unnecessary white space
</blockquote></details>

Done.

**Pull request merged**
