### PR TITLE
App bar created

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/270)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/270)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/button/AppBarButton.kt, line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/270#-MZEMVrME1PZrqYCJVzX:-MZEMVrME1PZrqYCJVzY:b-wlnd08) ([raw file](https://github.com/bible-translation-tools/orature/blob/74cee4dc918a45fe58787c47ab9a5ec419c3c2e2/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/button/AppBarButton.kt#L15)):*
> ```Kotlin
> import tornadofx.*
> 
> class AppBarButton : Control() {
> ```

Is there a reason you don't extend Button or just reskin a Button? For the most part it feels like you could at least accomplish this from something like:

button(messages["text"], FontIcon()) {
    styleClass.addAll("app-bar-button")
    style {
        skin = AppBarButtonSkin
    }
}
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 31 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/270#-MZEMn6JD7HGAA-PSfiw:-MZEMn6JD7HGAA-PSfix:bsh87p3) ([raw file](https://github.com/bible-translation-tools/orature/blob/74cee4dc918a45fe58787c47ab9a5ec419c3c2e2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L31)):*
> ```Kotlin
>                     btnTextProperty.set(messages["add"])
>                     btnIconProperty.set(FontIcon(MaterialDesign.MDI_PLUS))
>                 }
> ```

Probably best to do:

val addBtn = AppBarButton().apply {
}

init {
...
add(addBtn)
...
}

alternatively you could store a list of pairs of text, icon and iterate over that in a for loop here

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/270)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/button/AppBarButton.kt, line 15 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/270#-MZEMVrME1PZrqYCJVzX:-MZHqCvH3J9WWvShIrOB:b-g3058p) ([raw file](https://github.com/bible-translation-tools/orature/blob/74cee4dc918a45fe58787c47ab9a5ec419c3c2e2/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/button/AppBarButton.kt#L15)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Is there a reason you don't extend Button or just reskin a Button? For the most part it feels like you could at least accomplish this from something like:

button(messages["text"], FontIcon()) {
    styleClass.addAll("app-bar-button")
    style {
        skin = AppBarButtonSkin
    }
}
</blockquote></details>

It doesn't work well this way. If I do that, Label is added above container in the skin and breaks the design of the button. Also I have added :active pseudo selector to the button. I would leave it as it is.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 31 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/270#-MZEMn6JD7HGAA-PSfiw:-MZHrFHl1kRCQ7uI4F2R:b-psgpgt) ([raw file](https://github.com/bible-translation-tools/orature/blob/74cee4dc918a45fe58787c47ab9a5ec419c3c2e2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L31)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Probably best to do:

val addBtn = AppBarButton().apply {
}

init {
...
add(addBtn)
...
}

alternatively you could store a list of pairs of text, icon and iterate over that in a for loop here
</blockquote></details>

Done. I wouldn't do it using list of pairs, because there would be different actions for buttons and maybe more things

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/270)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt, line 31 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/270#-MZEMn6JD7HGAA-PSfiw:-MZJiMWcAcQ5_96N9TCv:b7e0zr5) ([raw file](https://github.com/bible-translation-tools/orature/blob/74cee4dc918a45fe58787c47ab9a5ec419c3c2e2/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L31)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done. I wouldn't do it using list of pairs, because there would be different actions for buttons and maybe more things
</blockquote></details>

Refactored to extend ToggleButton

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/270#-:-MZOTQD4CDXf4WNZlkbI:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @mXaln)

**Pull request merged**
