### PR TITLE
Select other take when deleting first one

### PR DESCRIPTION
**Pull request by AnonymousWalker**
- Selects the first take when a previously selected is deleted
- Animation for deleting a take
- Update timestamp when take is selected

---
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)

### CODE REVIEW

**Review by mXaln — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-Mnkm1Bi7z7Ru8xqG-ND:bre6qe8) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
> ```Kotlin
>         closePlayers()
>         contextProperty.set(pluginType)
>         takeEvent.take.file.setLastModified(System.currentTimeMillis())
> ```

There is no need to modify the files attributes before opening it in a plugin. When the files is changed in the plugin, its attributes change as well. But if you cancel modification to the file (do nothing to the file in the plugin), we shouldn't modify it manually.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-MnknELyCmPspEryyWP_:b-6i9z6i) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

There is no need to modify the files attributes before opening it in a plugin. When the files is changed in the plugin, its attributes change as well. But if you cancel modification to the file (do nothing to the file in the plugin), we shouldn't modify it manually.  
</blockquote></details>

When we edit a take, it becomes selected and stays on top of the list. To make it consistent with selecting a take, I also set the modified timestamp.
After discussing with Joe about which actions should update the modified timestamp, it appears that any time the user "touches" the file, it should update the timestamp

**Review by mXaln — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-MnksXwpBr5ANLGS3EKM:b-rajz0p) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
<details><summary><i>Previously, AnonymousWalker (Tony Anh Tran) wrote…</i></summary><blockquote>

When we edit a take, it becomes selected and stays on top of the list. To make it consistent with selecting a take, I also set the modified timestamp.
After discussing with Joe about which actions should update the modified timestamp, it appears that any time the user "touches" the file, it should update the timestamp
</blockquote></details>

Well actually it that already. If you look at TakeActions.kt, edit and mark functions do select take when you quit plugin.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-Mnl8cYS3ljhV0IlPxha:b-z8eio2) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Well actually it that already. If you look at TakeActions.kt, edit and mark functions do select take when you quit plugin.
</blockquote></details>

the timestamp isn't updated when opening with a plugin.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: all files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-MnlfwYq2hB6buN66Ju5:bb14h86) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
<details><summary><i>Previously, AnonymousWalker (Tony Anh Tran) wrote…</i></summary><blockquote>

the timestamp isn't updated when opening with a plugin.
</blockquote></details>

Regardless, I think this should be done model-side, not in the viewmodel.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt, line 281 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/415#-Mnkm1Bi7z7Ru8xqG-NC:-MnlkM4N07O8o3vgO5-V:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/f4f7c85687d32a10a1fb31a4fd4f7bfddc8d59c8/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/RecordScriptureViewModel.kt#L281)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Regardless, I think this should be done model-side, not in the viewmodel.
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/TakeActions.kt, line 198 at r5](https://reviewable.io/reviews/bible-translation-tools/orature/415#-MnlkwytEUpLRmlIMbDm:-MnlkwytEUpLRmlIMbDn:bp22i49) ([raw file](https://github.com/bible-translation-tools/orature/blob/d6d82da723e49fd9e5993a026962ca98b3e62964/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/TakeActions.kt#L198)):*
> ```Kotlin
>         result: Result
>     ): Result {
>         take.file.setLastModified(System.currentTimeMillis())
> ```

if this is by definition part of what "selects a take," then should this not exist in the function immediately below?

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/415#-:-MoKQn8j0Ptul3E6Ek3t:bnfp4nl)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

**Pull request merged**
